name: Update Pool League Rankings
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  update-rankings:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Match Results') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install @octokit/rest
        
    - name: Update rankings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: node .github/scripts/update-rankings.mjs
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update rankings from match results"
          git push
        fi